// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnubfpxeopegsmbnywlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhudWJmcHhlb3BlZ3NtYm55d2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjIwNTUsImV4cCI6MjA2OTYzODA1NX0.v-VbA6Na4HZ6FVzbBZo_kR0m4pRx5iA9MBnw35G2vMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});